name: Generate GHBall Animation

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Generate GHBall animation
      - uses: Sayad-Uddin-Tahsin/GHBall@main
        with:
          username: ${{ github.repository_owner }}

      # Push contents to the "GHBall" branch
      - name: Push to GHBall branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: GHBall
          build_dir: output
          commit_message: "Update GHBall animations"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
